name: WebdriverIO Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Install Dependencies
          run: npm install

        - name: Test
          run: npm run wdio
          continue-on-error: true

        - name: Generate report
          run: npm run allure:generate

        - name: Upload Reports
          uses: actions/upload-artifact@v4
          with:
            name: allure-reports
            path: allure-report